# Generated by Django 5.1.2 on 2024-10-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_usuario_dono_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_permissions', to='auth.permission'),
        ),
    ]
